#version: "3.0"

version: '2.0'

services:
   python-app:
         build: ../Dockerfileprac

   bashapp:
         image: ububtu:latest
         stdin_open: true
         tty: true
         command: /bin/bash